version: "3.8"
services:
  chat_server:
    build:
    container_name : chat_server
    ports: 
    - "5000:5000"
    networks:
      app_net:
        ipv4_address: 192.168.2.100

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
